---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

setwd("C:/Users/Anhuynh/Desktop/Data Science_Cousera/Reproducible Research/Assignment")
if(!file.exists("data1")) {
        dir.create("data1")
}
fileUrl <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip"
download.file(fileUrl, destfile = "./data1/activity.zip")
library(readr)
data = read_csv("./data1/activity.zip")


## What is mean total number of steps taken per day?

### 1. Make a histogram of the total number of steps taken each day
library(dplyr)
data_fixed <- data[!is.na(data$steps), ]
subgroup_date <- ddply(data_fixed, ~date, summarise, sum = sum(steps))

hist(subgroup_date$sum, col = "green")
rug(subgroup_date$sum)
abline(v = median(subgroup_date$sum, na.rm=TRUE), col = "magenta", lwd = 4)
abline(v = mean(subgroup_date$sum, na.rm=TRUE), col = "blue", lwd = 3)
legend("topright", pch = 15, col=c("magenta", "blue"), legend=c("Median", "Mean"))

### 2. Calculate and report the mean and median total number of steps taken per day

#the mean total number of steps taken per day
library(dplyr)
data_fixed <- data[!is.na(data$steps), ]
subgroup_date <- ddply(data_fixed, ~date, summarise, sum = sum(steps))
mean(subgroup_date$sum)

median(subgroup_date$sum)

## What is the average daily activity pattern?

### Make a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)
subgroup_interval <- ddply(data_fixed, ~interval, summarise, mean=mean(steps))
with(subgroup_interval, plot(interval, mean, type = "p", col = "darkgreen", main = "Average Daily Activity", xlab = "Interval", ylab = "Number of steps"))


subgroup_interval <- ddply(data_fixed, ~interval, summarise, mean=mean(steps))
with(subgroup_interval, plot(interval, mean, type = "p", col = "darkgreen", main = "Average Daily Activity", xlab = "Interval", ylab = "Number of steps"))
abline(v = subgroup_interval$interval[which.max(subgroup_interval$mean)], col = "green", lwd = 2)

### Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
# determine max value
maxVal <- max(subgroup_interval$mean)
print(maxVal)
maxLine <- subgroup_interval[subgroup_interval$mean == maxVal, ]
# find the interval
maxInterval <- maxLine$interval
print(maxInterval)

## Imputing missing values

### Note that there are a number of days/intervals where there are missing values (coded as NA). The presence of missing days may introduce bias into some calculations or summaries of the data.

1. Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)

sum(is.na(data))

# Percentage of missing data over a dataset (4.37%)
mean(is.na(data))

2. Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc.

Option 1: Replacing all missing features values by the same constant/mean or median of the attribute

Option 2: using the most probable value to fill in the missing value (e.g. regression, inference-based tools using Bayesian formalism or decision tree induction)

3. Create a new dataset that is equal to the original dataset but with the missing data filled in.

# replace a subset of columns ("steps") with their median

library(dplyr)
newData <- data %>% 
    mutate_at(vars(steps), ~ifelse(is.na(.), median(., na.rm = TRUE), .))

dim(data)
dim(newData)

4. Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day. Do these values differ from the estimates from the first part of the assignment? What is the impact of imputing missing data on the estimates of the total daily number of steps?

# the impact of imputing missing data on the estimates of the total daily number of steps keeps value of median and mean of new dataset less than the original one (refer to two histograms built for visualization)
totalstep <- tapply(newData$steps, newData$date, sum)
hist(totalstep, col = "gold")
rug(totalstep)
abline(v = median(totalstep, na.rm=TRUE), col = "magenta", lwd = 4)
abline(v = mean(totalstep, na.rm=TRUE), col = "blue", lwd = 4)
legend("topright", pch = 15, col=c("magenta", "blue"), legend=c("Median", "Mean"))

# the mean total number of steps taken per day
library(dplyr)
new_subgroup_date <- ddply(newData, ~date, summarise, sum = sum(steps))
mean(new_subgroup_date$sum)

# the median total number of steps taken per day
median(new_subgroup_date$sum)

## Are there differences in activity patterns between weekdays and weekends?

### For this part the weekdays() function may be of some help here. Use the dataset with the filled-in missing values for this part.

1. Create a new factor variable in the dataset with two levels -- "weekday" and "weekend" indicating whether a given date is a weekday or weekend day.

# add a new column containing day of week
weekday_newData = weekdays(newData$date)
# add a new column containing either Weekday OR Weekend
dateType <- ifelse(weekday_newData == "Saturday" | weekday_newData == 
    "Sunday", "Weekend", "Weekday")
# convert column to factor
dateType_factor <- factor(dateType)

2. Make a panel plot containing a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis). The plot should look something like the following, which was created using simulated data:

# make a new dataset grouping data by interval and weekday[type]
library(plyr)
groupedBy_int_dat <- ddply(newData, .(interval, dateType_factor), summarise, 
    mean = mean(steps, na.rm = TRUE))

# get the level of numeric values
groupedBy_int_dat$interval <- as.numeric(as.character(groupedBy_int_dat$interval))
library(lattice)
xyplot(mean ~ interval | dateType_factor, groupedBy_int_dat, type = "l", 
    layout = c(1, 2), xlab = "Interval", ylab = "Number of steps")
